# Generated by Django 4.2.7 on 2023-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(db_column='Admin_id', primary_key=True, serialize=False)),
                ('admin_name', models.CharField(db_column='Admin_name', max_length=200)),
                ('password', models.CharField(db_column='Password', max_length=200)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_name', models.CharField(db_column='Location_name', max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=5000)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_fare', models.IntegerField()),
                ('no_of_ticket', models.IntegerField()),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('capacity', models.IntegerField(primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='class', max_length=200)),
                ('ticket_price', models.IntegerField()),
            ],
            options={
                'db_table': 'seats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival_time', models.IntegerField(db_column='Arrival_time')),
                ('depart_time', models.IntegerField(db_column='Depart_time')),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.IntegerField(db_column='Train_No', primary_key=True, serialize=False)),
                ('name_of_trains', models.CharField(blank=True, db_column='Name_of_Trains', max_length=512, null=True)),
                ('off_day', models.CharField(blank=True, db_column='Off_day', max_length=512, null=True)),
                ('starting_station', models.CharField(blank=True, db_column='Starting_Station', max_length=512, null=True)),
                ('departure_time', models.CharField(blank=True, db_column='Departure_Time', max_length=512, null=True)),
                ('arrival_station', models.CharField(blank=True, db_column='Arrival_station', max_length=512, null=True)),
                ('arrival_time', models.CharField(blank=True, db_column='Arrival_Time', max_length=512, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
